export type CalendarCategory =
  | "class"
  | "sacrament"
  | "parent"
  | "event"
  | "break"
  | "holiday"
  | "registration"
  | "other";

export type CalendarEvent = {
  id: string;
  title: string;
  date: string;
  endDate?: string;
  time?: string;
  category: CalendarCategory;
  location?: string;
  notes: string;
};

export const calendarCategoryLabels: Record<CalendarCategory, string> = {
  class: "Class",
  sacrament: "Sacramental preparation",
  parent: "Parent meeting",
  event: "Special event",
  break: "Break",
  holiday: "Holiday",
  registration: "Registration",
  other: "Other",
};

export const calendarGuideline =
  "Please note: The Religious Education calendar is a general guideline and may be subject to change. Please check announcements for the most current information.";

const parishLocation = "St. Mary, Star of the Sea, 1465 Grand Avenue";

export const educationCalendarEvents: CalendarEvent[] = [
  {
    id: "re-registration",
    title: "Religious Education registration",
    date: "August",
    category: "registration",
    location: "Parish Office, 1465 Grand Avenue",
    notes:
      "Registration begins in August. Call (503) 325-3671 or write to Marty Dursse at marty@stmaryastoria.com. If you are new to the parish, please call the office.",
  },
  {
    id: "daily-mass-pause",
    title: "Daily Masses paused",
    date: "2026-08-11",
    endDate: "2026-09-02",
    category: "break",
    location: "St. Mary, Star of the Sea",
    notes:
      "The parish has announced that daily Masses are cancelled from August 11 through September 2. Sunday Mass continues as published. See announcements for the latest word.",
  },
  {
    id: "sunday-mass",
    title: "Sunday Mass at St. Mary",
    date: "Sundays",
    time: "8:30 a.m., 10:30 a.m., and Noon (Spanish)",
    category: "other",
    location: "St. Mary, Star of the Sea, 1465 Grand Avenue",
    notes: "Wheelchair accessible through the 15th Street side door.",
  },
  {
    id: "vigil-mass",
    title: "Saturday Vigil Mass",
    date: "Saturdays",
    time: "4:00 p.m.",
    category: "other",
    location: "St. Francis de Sales Mission, Hammond",
    notes: "The Rosary is prayed a half hour before the 4:00 p.m. Vigil Mass.",
  },
  {
    id: "confirmation-cycle",
    title: "Confirmation",
    date: "Every two years",
    category: "sacrament",
    notes:
      "Religious Education coordinates sacramental preparation for Confirmation. The Rite of Confirmation occurs every two years. Ask the Religious Education office for the current cycle.",
  },
  {
    id: "2026-09-13-first-class",
    title: "First Class",
    date: "2026-09-13",
    category: "class",
    location: parishLocation,
    notes: "Faith & the Holy Trinity",
  },
  {
    id: "2026-09-16-ocia",
    title: "OCIA",
    date: "2026-09-16",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2026-09-17-ocic",
    title: "OCIC",
    date: "2026-09-17",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2026-09-20-all-classes",
    title: "All Classes",
    date: "2026-09-20",
    category: "class",
    location: parishLocation,
    notes: "All Classes",
  },
  {
    id: "2026-09-22-parent-orientation",
    title: "Parent Religious Education Orientation",
    date: "2026-09-22",
    time: "7:00 p.m.",
    category: "parent",
    location: parishLocation,
    notes: "Parent Religious Education Orientation",
  },
  {
    id: "2026-09-23-ocia",
    title: "OCIA",
    date: "2026-09-23",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2026-09-24-ocic",
    title: "OCIC",
    date: "2026-09-24",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2026-09-27-all-classes",
    title: "All Classes",
    date: "2026-09-27",
    category: "class",
    location: parishLocation,
    notes: "All Classes",
  },
  {
    id: "2026-09-30-ocia",
    title: "OCIA",
    date: "2026-09-30",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2026-10-01-ocic",
    title: "OCIC",
    date: "2026-10-01",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2026-10-04-all-classes",
    title: "All Classes",
    date: "2026-10-04",
    category: "class",
    location: parishLocation,
    notes: "All Classes",
  },
  {
    id: "2026-10-07-ocia",
    title: "OCIA",
    date: "2026-10-07",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2026-10-08-ocic",
    title: "OCIC",
    date: "2026-10-08",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2026-10-11-all-classes",
    title: "All Classes",
    date: "2026-10-11",
    category: "class",
    location: parishLocation,
    notes: "All Classes",
  },
  {
    id: "2026-10-14-ocia",
    title: "OCIA",
    date: "2026-10-14",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2026-10-15-ocic",
    title: "OCIC",
    date: "2026-10-15",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2026-10-18-all-classes",
    title: "All Classes",
    date: "2026-10-18",
    category: "class",
    location: parishLocation,
    notes: "All Classes",
  },
  {
    id: "2026-10-21-ocia",
    title: "OCIA",
    date: "2026-10-21",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2026-10-22-ocic",
    title: "OCIC",
    date: "2026-10-22",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2026-10-25-all-classes",
    title: "All Classes",
    date: "2026-10-25",
    category: "class",
    location: parishLocation,
    notes: "Child Safety Training",
  },
  {
    id: "2026-10-28-ocia",
    title: "OCIA",
    date: "2026-10-28",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2026-10-29-ocic",
    title: "OCIC",
    date: "2026-10-29",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2026-11-01-all-classes",
    title: "All Classes",
    date: "2026-11-01",
    category: "class",
    location: parishLocation,
    notes: "All Classes",
  },
  {
    id: "2026-11-04-ocia",
    title: "OCIA",
    date: "2026-11-04",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2026-11-05-ocic",
    title: "OCIC",
    date: "2026-11-05",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2026-11-08-all-classes",
    title: "All Classes",
    date: "2026-11-08",
    category: "class",
    location: parishLocation,
    notes: "All Classes",
  },
  {
    id: "2026-11-11-ocia",
    title: "OCIA",
    date: "2026-11-11",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2026-11-12-ocic",
    title: "OCIC",
    date: "2026-11-12",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2026-11-15-all-classes",
    title: "All Classes",
    date: "2026-11-15",
    category: "class",
    location: parishLocation,
    notes: "All Classes",
  },
  {
    id: "2026-11-18-ocia",
    title: "OCIA",
    date: "2026-11-18",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2026-11-19-ocic",
    title: "OCIC",
    date: "2026-11-19",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2026-11-22-all-classes",
    title: "All Classes",
    date: "2026-11-22",
    category: "class",
    location: parishLocation,
    notes: "All Classes",
  },
  {
    id: "2026-11-26-thanksgiving",
    title: "Thanksgiving Day",
    date: "2026-11-26",
    category: "holiday",
    notes: "Thanksgiving Day",
  },
  {
    id: "2026-11-29-no-classes",
    title: "NO CLASSES / Thanksgiving Break",
    date: "2026-11-29",
    category: "break",
    notes: "First Sunday in Advent",
  },
  {
    id: "2026-12-06-all-classes",
    title: "All Classes",
    date: "2026-12-06",
    category: "class",
    location: parishLocation,
    notes: "Second Sunday in Advent",
  },
  {
    id: "2026-12-09-ocia",
    title: "OCIA",
    date: "2026-12-09",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2026-12-10-ocic",
    title: "OCIC",
    date: "2026-12-10",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2026-12-13-all-classes",
    title: "All Classes",
    date: "2026-12-13",
    category: "class",
    location: parishLocation,
    notes: "Third Sunday in Advent",
  },
  {
    id: "2026-12-16-ocia",
    title: "OCIA",
    date: "2026-12-16",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2026-12-17-ocic",
    title: "OCIC",
    date: "2026-12-17",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2026-12-20-all-classes",
    title: "All Classes",
    date: "2026-12-20",
    category: "class",
    location: parishLocation,
    notes: "Fourth Sunday in Advent",
  },
  {
    id: "2026-12-25-nativity",
    title: "The Nativity of the Lord",
    date: "2026-12-25",
    category: "holiday",
    notes: "The Nativity of the Lord",
  },
  {
    id: "2026-12-27-no-classes",
    title: "NO CLASSES / Christmas Break",
    date: "2026-12-27",
    category: "break",
    notes: "NO CLASSES / Christmas Break",
  },
  {
    id: "2027-01-01-new-year",
    title: "New Year's Day",
    date: "2027-01-01",
    category: "holiday",
    notes: "New Year's Day",
  },
  {
    id: "2027-01-03-no-classes",
    title: "NO CLASSES",
    date: "2027-01-03",
    category: "break",
    notes: "NO CLASSES",
  },
  {
    id: "2027-01-10-all-classes",
    title: "All Classes",
    date: "2027-01-10",
    category: "class",
    location: parishLocation,
    notes: "All Classes",
  },
  {
    id: "2027-01-13-ocia",
    title: "OCIA",
    date: "2027-01-13",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2027-01-14-ocic",
    title: "OCIC",
    date: "2027-01-14",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2027-01-17-no-classes",
    title: "NO CLASSES / MLK Holiday Weekend",
    date: "2027-01-17",
    category: "break",
    notes: "NO CLASSES / MLK Holiday Weekend",
  },
  {
    id: "2027-01-20-ocia",
    title: "OCIA",
    date: "2027-01-20",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2027-01-21-ocic",
    title: "OCIC",
    date: "2027-01-21",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2027-01-24-all-classes",
    title: "All Classes",
    date: "2027-01-24",
    category: "class",
    location: parishLocation,
    notes: "All Classes",
  },
  {
    id: "2027-01-27-ocia",
    title: "OCIA",
    date: "2027-01-27",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2027-01-28-ocic",
    title: "OCIC",
    date: "2027-01-28",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2027-02-07-all-classes",
    title: "All Classes",
    date: "2027-02-07",
    category: "class",
    location: parishLocation,
    notes: "All Classes",
  },
  {
    id: "2027-02-10-ash-wednesday",
    title: "Ash Wednesday",
    date: "2027-02-10",
    category: "holiday",
    notes: "Ash Wednesday",
  },
  {
    id: "2027-02-11-ocia-ocic",
    title: "OCIA / OCIC",
    date: "2027-02-11",
    category: "class",
    location: parishLocation,
    notes: "OCIA / OCIC",
  },
  {
    id: "2027-02-14-no-classes",
    title: "NO CLASSES / President's Day Weekend / First Sunday in Lent",
    date: "2027-02-14",
    category: "break",
    notes: "OCIA/OCIC Rite of Election",
  },
  {
    id: "2027-02-21-all-classes",
    title: "All Classes",
    date: "2027-02-21",
    category: "class",
    location: parishLocation,
    notes: "Second Sunday in Lent",
  },
  {
    id: "2027-02-24-ocia",
    title: "OCIA",
    date: "2027-02-24",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2027-02-25-ocic",
    title: "OCIC",
    date: "2027-02-25",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2027-02-28-all-classes",
    title: "All Classes",
    date: "2027-02-28",
    category: "class",
    location: parishLocation,
    notes: "Third Sunday in Lent (OCIA/OCIC First Scrutiny)",
  },
  {
    id: "2027-03-03-ocia",
    title: "OCIA",
    date: "2027-03-03",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2027-03-04-ocic",
    title: "OCIC",
    date: "2027-03-04",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2027-03-07-all-classes",
    title: "All Classes",
    date: "2027-03-07",
    category: "class",
    location: parishLocation,
    notes: "Fourth Sunday in Lent (OCIA/OCIC Second Scrutiny)",
  },
  {
    id: "2027-03-10-ocia",
    title: "OCIA",
    date: "2027-03-10",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2027-03-11-ocic",
    title: "OCIC",
    date: "2027-03-11",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2027-03-14-all-classes",
    title: "All Classes",
    date: "2027-03-14",
    category: "class",
    location: parishLocation,
    notes: "Fifth Sunday in Lent (OCIA/OCIC Third Scrutiny)",
  },
  {
    id: "2027-03-17-ocia",
    title: "OCIA",
    date: "2027-03-17",
    category: "class",
    location: parishLocation,
    notes: "OCIA",
  },
  {
    id: "2027-03-18-ocic",
    title: "OCIC",
    date: "2027-03-18",
    category: "class",
    location: parishLocation,
    notes: "OCIC",
  },
  {
    id: "2027-03-21-no-classes",
    title: "NO CLASSES / Spring Break / Palm Sunday",
    date: "2027-03-21",
    category: "break",
    notes: "NO CLASSES / Spring Break / Palm Sunday",
  },
  {
    id: "2027-03-25-holy-thursday",
    title: "Holy Thursday",
    date: "2027-03-25",
    category: "holiday",
    notes: "Holy Thursday",
  },
  {
    id: "2027-03-26-good-friday",
    title: "Good Friday",
    date: "2027-03-26",
    category: "holiday",
    notes: "Good Friday",
  },
  {
    id: "2027-03-27-holy-saturday",
    title: "Holy Saturday",
    date: "2027-03-27",
    category: "holiday",
    notes: "Holy Saturday",
  },
  {
    id: "2027-03-28-resurrection",
    title: "The Resurrection of the Lord / NO CLASSES",
    date: "2027-03-28",
    category: "holiday",
    notes: "The Resurrection of the Lord / NO CLASSES",
  },
];
