export type Prayer = {
  id: string;
  title: string;
  latin?: string;
  note?: string;
  lines: string[];
};

export type PrayerCategory = {
  id: string;
  label: string;
  navLabel: string;
  description: string;
  prayers: Prayer[];
};

const hailMary = [
  "Hail Mary, full of grace, the Lord is with thee;",
  "blessed art thou among women,",
  "and blessed is the fruit of thy womb, Jesus.",
  "Holy Mary, Mother of God,",
  "pray for us sinners,",
  "now and at the hour of our death. Amen.",
];

export const prayerCategories: PrayerCategory[] = [
  {
    id: "essential",
    label: "Essential Prayers",
    navLabel: "Essential Prayers",
    description:
      "The prayers Catholics learn first — the Creed, the Lord's Prayer, the Hail Mary, and the Glory Be.",
    prayers: [
      {
        id: "apostles-creed",
        title: "Apostles' Creed",
        note: "A brief summary of the faith, often prayed with the Rosary.",
        lines: [
          "I believe in God,",
          "the Father almighty,",
          "Creator of heaven and earth,",
          "and in Jesus Christ, his only Son, our Lord,",
          "who was conceived by the Holy Spirit,",
          "born of the Virgin Mary,",
          "suffered under Pontius Pilate,",
          "was crucified, died and was buried;",
          "he descended into hell;",
          "on the third day he rose again from the dead;",
          "he ascended into heaven,",
          "and is seated at the right hand of God the Father almighty;",
          "from there he will come to judge the living and the dead.",
          "I believe in the Holy Spirit,",
          "the holy catholic Church,",
          "the communion of saints,",
          "the forgiveness of sins,",
          "the resurrection of the body,",
          "and life everlasting. Amen.",
        ],
      },
      {
        id: "our-father",
        title: "Our Father",
        latin: "The Lord's Prayer",
        lines: [
          "Our Father, who art in heaven,",
          "hallowed be thy name;",
          "thy kingdom come;",
          "thy will be done",
          "on earth as it is in heaven.",
          "Give us this day our daily bread;",
          "and forgive us our trespasses",
          "as we forgive those who trespass against us;",
          "and lead us not into temptation,",
          "but deliver us from evil. Amen.",
        ],
      },
      {
        id: "hail-mary",
        title: "Hail Mary",
        latin: "Ave Maria",
        lines: hailMary,
      },
      {
        id: "glory-be",
        title: "Glory Be",
        latin: "Doxology",
        lines: [
          "Glory be to the Father, and to the Son, and to the Holy Spirit,",
          "as it was in the beginning, is now, and ever shall be,",
          "world without end. Amen.",
        ],
      },
    ],
  },
  {
    id: "mass",
    label: "Prayers Found Within the Mass",
    navLabel: "Mass Prayers",
    description:
      "Prayers of the liturgy — the words you will hear, and in time speak, at Mass.",
    prayers: [
      {
        id: "confiteor",
        title: "Confiteor",
        note: "Strike your breast at the words “through my fault.”",
        lines: [
          "I confess to almighty God",
          "and to you, my brothers and sisters,",
          "that I have greatly sinned,",
          "in my thoughts and in my words,",
          "in what I have done and in what I have failed to do,",
          "through my fault, through my fault,",
          "through my most grievous fault;",
          "therefore I ask blessed Mary ever-Virgin,",
          "all the Angels and Saints,",
          "and you, my brothers and sisters,",
          "to pray for me to the Lord our God.",
        ],
      },
      {
        id: "gloria",
        title: "Gloria in Excelsis",
        latin: "Glory to God in the highest",
        lines: [
          "Glory to God in the highest,",
          "and on earth peace to people of good will.",
          "We praise you,",
          "we bless you,",
          "we adore you,",
          "we glorify you,",
          "we give you thanks for your great glory,",
          "Lord God, heavenly King,",
          "O God, almighty Father.",
          "Lord Jesus Christ, Only Begotten Son,",
          "Lord God, Lamb of God, Son of the Father,",
          "you take away the sins of the world, have mercy on us;",
          "you take away the sins of the world, receive our prayer;",
          "you are seated at the right hand of the Father, have mercy on us.",
          "For you alone are the Holy One,",
          "you alone are the Lord,",
          "you alone are the Most High,",
          "Jesus Christ,",
          "with the Holy Spirit,",
          "in the glory of God the Father. Amen.",
        ],
      },
      {
        id: "nicene-creed",
        title: "Nicene Creed",
        note: "Bow at the words “and by the Holy Spirit was incarnate of the Virgin Mary, and became man.”",
        lines: [
          "I believe in one God,",
          "the Father almighty,",
          "maker of heaven and earth,",
          "of all things visible and invisible.",
          "I believe in one Lord Jesus Christ,",
          "the Only Begotten Son of God,",
          "born of the Father before all ages.",
          "God from God, Light from Light,",
          "true God from true God,",
          "begotten, not made, consubstantial with the Father;",
          "through him all things were made.",
          "For us men and for our salvation",
          "he came down from heaven,",
          "and by the Holy Spirit was incarnate of the Virgin Mary,",
          "and became man.",
          "For our sake he was crucified under Pontius Pilate,",
          "he suffered death and was buried,",
          "and rose again on the third day",
          "in accordance with the Scriptures.",
          "He ascended into heaven",
          "and is seated at the right hand of the Father.",
          "He will come again in glory",
          "to judge the living and the dead",
          "and his kingdom will have no end.",
          "I believe in the Holy Spirit, the Lord, the giver of life,",
          "who proceeds from the Father and the Son,",
          "who with the Father and the Son is adored and glorified,",
          "who has spoken through the prophets.",
          "I believe in one, holy, catholic and apostolic Church.",
          "I confess one Baptism for the forgiveness of sins",
          "and I look forward to the resurrection of the dead",
          "and the life of the world to come. Amen.",
        ],
      },
      {
        id: "sanctus",
        title: "Sanctus",
        latin: "Holy, Holy, Holy",
        lines: [
          "Holy, Holy, Holy Lord God of hosts.",
          "Heaven and earth are full of your glory.",
          "Hosanna in the highest.",
          "Blessed is he who comes in the name of the Lord.",
          "Hosanna in the highest.",
        ],
      },
      {
        id: "agnus-dei",
        title: "Agnus Dei",
        latin: "Lamb of God",
        lines: [
          "Lamb of God, you take away the sins of the world, have mercy on us.",
          "Lamb of God, you take away the sins of the world, have mercy on us.",
          "Lamb of God, you take away the sins of the world, grant us peace.",
        ],
      },
      {
        id: "spiritual-communion",
        title: "Act of Spiritual Communion",
        note: "A prayer of desire for Jesus in the Eucharist when you cannot receive Holy Communion.",
        lines: [
          "My Jesus,",
          "I believe that You are present in the Most Holy Sacrament.",
          "I love You above all things,",
          "and I desire to receive You into my soul.",
          "Since I cannot at this moment receive You sacramentally,",
          "come at least spiritually into my heart.",
          "I embrace You as if You were already there",
          "and unite myself wholly to You.",
          "Never permit me to be separated from You. Amen.",
        ],
      },
    ],
  },
  {
    id: "devotions",
    label: "Marian & Devotional Prayers",
    navLabel: "Devotions",
    description:
      "Prayers of trust, mercy, and protection — companions for the Rosary, for evening, and for a contrite heart.",
    prayers: [
      {
        id: "salve-regina",
        title: "Hail, Holy Queen",
        latin: "Salve Regina",
        lines: [
          "Hail, Holy Queen, Mother of Mercy,",
          "our life, our sweetness and our hope.",
          "To thee do we cry, poor banished children of Eve.",
          "To thee do we send up our sighs,",
          "mourning and weeping in this valley of tears.",
          "Turn then, most gracious advocate,",
          "thine eyes of mercy toward us,",
          "and after this our exile,",
          "show unto us the blessed fruit of thy womb, Jesus.",
          "O clement, O loving, O sweet Virgin Mary.",
          "V. Pray for us, O holy Mother of God.",
          "R. That we may be made worthy of the promises of Christ.",
        ],
      },
      {
        id: "memorare",
        title: "Memorare",
        lines: [
          "Remember, O most gracious Virgin Mary,",
          "that never was it known that anyone who fled to thy protection,",
          "implored thy help, or sought thy intercession was left unaided.",
          "Inspired by this confidence, I fly unto thee, O Virgin of virgins, my Mother;",
          "to thee do I come, before thee I stand, sinful and sorrowful.",
          "O Mother of the Word Incarnate, despise not my petitions,",
          "but in thy mercy hear and answer me. Amen.",
        ],
      },
      {
        id: "angelus",
        title: "The Angelus",
        note: "Traditionally prayed in the morning, at noon, and in the evening.",
        lines: [
          "V. The Angel of the Lord declared unto Mary.",
          "R. And she conceived of the Holy Spirit.",
          ...hailMary,
          "V. Behold the handmaid of the Lord.",
          "R. Be it done unto me according to thy word.",
          ...hailMary,
          "V. And the Word was made flesh.",
          "R. And dwelt among us.",
          ...hailMary,
          "V. Pray for us, O holy Mother of God.",
          "R. That we may be made worthy of the promises of Christ.",
          "Let us pray.",
          "Pour forth, we beseech Thee, O Lord, Thy grace into our hearts,",
          "that we, to whom the Incarnation of Christ Thy Son",
          "was made known by the message of an Angel,",
          "may by His Passion and Cross",
          "be brought to the glory of His Resurrection.",
          "Through the same Christ our Lord. Amen.",
        ],
      },
      {
        id: "st-michael",
        title: "Saint Michael the Archangel",
        lines: [
          "Saint Michael the Archangel, defend us in battle.",
          "Be our protection against the wickedness and snares of the devil.",
          "May God rebuke him, we humbly pray;",
          "and do thou, O Prince of the heavenly host,",
          "by the power of God,",
          "cast into hell Satan and all the evil spirits",
          "who prowl about the world seeking the ruin of souls. Amen.",
        ],
      },
      {
        id: "act-of-contrition",
        title: "Act of Contrition",
        note: "A traditional prayer of sorrow for sin, used in the Sacrament of Reconciliation and in daily examination of conscience.",
        lines: [
          "O my God, I am heartily sorry for having offended Thee,",
          "and I detest all my sins because of Thy just punishments,",
          "but most of all because they offend Thee, my God,",
          "Who art all good and deserving of all my love.",
          "I firmly resolve, with the help of Thy grace,",
          "to sin no more and to avoid the near occasion of sin. Amen.",
        ],
      },
    ],
  },
];
