export type ClassStatus = "upcoming" | "completed";

export type ClassSession = {
  id: string;
  date: string;
  time: string;
  title: string;
  topic: string;
  location: string;
  instructor: string;
};

const parishLocation = "St. Mary, Star of the Sea, 1465 Grand Avenue";
const reOffice = "Religious Education Office";
const dre = "Marty Dursse, Director of Religious Education";

/*
 * 2026–2027 Religious Education / OCIA calendar.
 * Weekly meeting hours are not posted for ordinary class days; do not invent them.
 */
export const classSchedule: ClassSession[] = [
  {
    id: "2026-09-13-first-class",
    date: "2026-09-13",
    time: "Weekly",
    title: "First Class",
    topic: "Faith & the Holy Trinity",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-09-16-ocia",
    date: "2026-09-16",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-09-17-ocic",
    date: "2026-09-17",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-09-20-all-classes",
    date: "2026-09-20",
    time: "Weekly",
    title: "All Classes",
    topic: "All Classes",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-09-22-parent-orientation",
    date: "2026-09-22",
    time: "7:00 p.m.",
    title: "Parent Religious Education Orientation",
    topic: "Parent Religious Education Orientation",
    location: parishLocation,
    instructor: dre,
  },
  {
    id: "2026-09-23-ocia",
    date: "2026-09-23",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-09-24-ocic",
    date: "2026-09-24",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-09-27-all-classes",
    date: "2026-09-27",
    time: "Weekly",
    title: "All Classes",
    topic: "All Classes",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-09-30-ocia",
    date: "2026-09-30",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-10-01-ocic",
    date: "2026-10-01",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-10-04-all-classes",
    date: "2026-10-04",
    time: "Weekly",
    title: "All Classes",
    topic: "All Classes",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-10-07-ocia",
    date: "2026-10-07",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-10-08-ocic",
    date: "2026-10-08",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-10-11-all-classes",
    date: "2026-10-11",
    time: "Weekly",
    title: "All Classes",
    topic: "All Classes",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-10-14-ocia",
    date: "2026-10-14",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-10-15-ocic",
    date: "2026-10-15",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-10-18-all-classes",
    date: "2026-10-18",
    time: "Weekly",
    title: "All Classes",
    topic: "All Classes",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-10-21-ocia",
    date: "2026-10-21",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-10-22-ocic",
    date: "2026-10-22",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-10-25-all-classes",
    date: "2026-10-25",
    time: "Weekly",
    title: "All Classes",
    topic: "Child Safety Training",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-10-28-ocia",
    date: "2026-10-28",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-10-29-ocic",
    date: "2026-10-29",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-11-01-all-classes",
    date: "2026-11-01",
    time: "Weekly",
    title: "All Classes",
    topic: "All Classes",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-11-04-ocia",
    date: "2026-11-04",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-11-05-ocic",
    date: "2026-11-05",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-11-08-all-classes",
    date: "2026-11-08",
    time: "Weekly",
    title: "All Classes",
    topic: "All Classes",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-11-11-ocia",
    date: "2026-11-11",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-11-12-ocic",
    date: "2026-11-12",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-11-15-all-classes",
    date: "2026-11-15",
    time: "Weekly",
    title: "All Classes",
    topic: "All Classes",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-11-18-ocia",
    date: "2026-11-18",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-11-19-ocic",
    date: "2026-11-19",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-11-22-all-classes",
    date: "2026-11-22",
    time: "Weekly",
    title: "All Classes",
    topic: "All Classes",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-11-26-thanksgiving",
    date: "2026-11-26",
    time: "",
    title: "Thanksgiving Day",
    topic: "Thanksgiving Day",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-11-29-no-classes",
    date: "2026-11-29",
    time: "",
    title: "NO CLASSES / Thanksgiving Break",
    topic: "First Sunday in Advent",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-12-06-all-classes",
    date: "2026-12-06",
    time: "Weekly",
    title: "All Classes",
    topic: "Second Sunday in Advent",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-12-09-ocia",
    date: "2026-12-09",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-12-10-ocic",
    date: "2026-12-10",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-12-13-all-classes",
    date: "2026-12-13",
    time: "Weekly",
    title: "All Classes",
    topic: "Third Sunday in Advent",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-12-16-ocia",
    date: "2026-12-16",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-12-17-ocic",
    date: "2026-12-17",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-12-20-all-classes",
    date: "2026-12-20",
    time: "Weekly",
    title: "All Classes",
    topic: "Fourth Sunday in Advent",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-12-25-nativity",
    date: "2026-12-25",
    time: "",
    title: "The Nativity of the Lord",
    topic: "The Nativity of the Lord",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2026-12-27-no-classes",
    date: "2026-12-27",
    time: "",
    title: "NO CLASSES / Christmas Break",
    topic: "NO CLASSES / Christmas Break",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-01-01-new-year",
    date: "2027-01-01",
    time: "",
    title: "New Year's Day",
    topic: "New Year's Day",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-01-03-no-classes",
    date: "2027-01-03",
    time: "",
    title: "NO CLASSES",
    topic: "NO CLASSES",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-01-10-all-classes",
    date: "2027-01-10",
    time: "Weekly",
    title: "All Classes",
    topic: "All Classes",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-01-13-ocia",
    date: "2027-01-13",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-01-14-ocic",
    date: "2027-01-14",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-01-17-no-classes",
    date: "2027-01-17",
    time: "",
    title: "NO CLASSES / MLK Holiday Weekend",
    topic: "NO CLASSES / MLK Holiday Weekend",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-01-20-ocia",
    date: "2027-01-20",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-01-21-ocic",
    date: "2027-01-21",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-01-24-all-classes",
    date: "2027-01-24",
    time: "Weekly",
    title: "All Classes",
    topic: "All Classes",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-01-27-ocia",
    date: "2027-01-27",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-01-28-ocic",
    date: "2027-01-28",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-02-07-all-classes",
    date: "2027-02-07",
    time: "Weekly",
    title: "All Classes",
    topic: "All Classes",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-02-10-ash-wednesday",
    date: "2027-02-10",
    time: "",
    title: "Ash Wednesday",
    topic: "Ash Wednesday",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-02-11-ocia-ocic",
    date: "2027-02-11",
    time: "Weekly",
    title: "OCIA / OCIC",
    topic: "OCIA / OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-02-14-no-classes",
    date: "2027-02-14",
    time: "",
    title: "NO CLASSES / President's Day Weekend / First Sunday in Lent",
    topic: "OCIA/OCIC Rite of Election",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-02-21-all-classes",
    date: "2027-02-21",
    time: "Weekly",
    title: "All Classes",
    topic: "Second Sunday in Lent",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-02-24-ocia",
    date: "2027-02-24",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-02-25-ocic",
    date: "2027-02-25",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-02-28-all-classes",
    date: "2027-02-28",
    time: "Weekly",
    title: "All Classes",
    topic: "Third Sunday in Lent (OCIA/OCIC First Scrutiny)",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-03-03-ocia",
    date: "2027-03-03",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-03-04-ocic",
    date: "2027-03-04",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-03-07-all-classes",
    date: "2027-03-07",
    time: "Weekly",
    title: "All Classes",
    topic: "Fourth Sunday in Lent (OCIA/OCIC Second Scrutiny)",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-03-10-ocia",
    date: "2027-03-10",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-03-11-ocic",
    date: "2027-03-11",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-03-14-all-classes",
    date: "2027-03-14",
    time: "Weekly",
    title: "All Classes",
    topic: "Fifth Sunday in Lent (OCIA/OCIC Third Scrutiny)",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-03-17-ocia",
    date: "2027-03-17",
    time: "Weekly",
    title: "OCIA",
    topic: "OCIA",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-03-18-ocic",
    date: "2027-03-18",
    time: "Weekly",
    title: "OCIC",
    topic: "OCIC",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-03-21-no-classes",
    date: "2027-03-21",
    time: "",
    title: "NO CLASSES / Spring Break / Palm Sunday",
    topic: "NO CLASSES / Spring Break / Palm Sunday",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-03-25-holy-thursday",
    date: "2027-03-25",
    time: "",
    title: "Holy Thursday",
    topic: "Holy Thursday",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-03-26-good-friday",
    date: "2027-03-26",
    time: "",
    title: "Good Friday",
    topic: "Good Friday",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-03-27-holy-saturday",
    date: "2027-03-27",
    time: "",
    title: "Holy Saturday",
    topic: "Holy Saturday",
    location: parishLocation,
    instructor: reOffice,
  },
  {
    id: "2027-03-28-resurrection",
    date: "2027-03-28",
    time: "",
    title: "The Resurrection of the Lord / NO CLASSES",
    topic: "The Resurrection of the Lord / NO CLASSES",
    location: parishLocation,
    instructor: reOffice,
  },
];

export function getClassStatus(date: string, today = getTodayIso()): ClassStatus {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return "upcoming";
  return date < today ? "completed" : "upcoming";
}

export function withStatus(session: ClassSession, today = getTodayIso()) {
  return { ...session, status: getClassStatus(session.date, today) };
}

function getTodayIso() {
  const now = new Date();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  return `${now.getFullYear()}-${month}-${day}`;
}

export function getUpcomingSessions(count = 4) {
  const today = getTodayIso();
  return classSchedule
    .filter((session) => getClassStatus(session.date, today) === "upcoming")
    .slice(0, count);
}

export function getNextSession() {
  return getUpcomingSessions(1)[0] ?? null;
}

export function getScheduleMonths() {
  const seen = new Set<string>();
  const months: { key: string; label: string }[] = [];

  for (const session of classSchedule) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(session.date)) continue;
    const key = session.date.slice(0, 7);
    if (seen.has(key)) continue;
    seen.add(key);
    const date = new Date(`${session.date}T12:00:00`);
    months.push({
      key,
      label: new Intl.DateTimeFormat("en-US", {
        month: "long",
        year: "numeric",
      }).format(date),
    });
  }

  return months;
}
